%% 计算Y坐标
%% 输入参数：
%   dStartPoseY: 初始y坐标
%   dStartYaw: 初始角度
%   dA0: 0阶系数
%   dA1: 1阶系数
%   dA2：2阶系数
%   dA3: 3阶系数
%   dS：总长度
%% 输出参数：
%   dPoseY：计算得到X坐标
%% 调用说明：

function dPoseY=CalcPoseY(dStartPoseY,dStartYaw,dA0,dA1,dA2,dA3,dS)
dPoseY=dStartPoseY+dS/24*(sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,0))+ ...
                        4*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS/8))+ ...
                        2*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*2/8))+ ...
                        4*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*3/8))+ ...
                        2*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*4/8))+ ...
                        4*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*5/8))+ ...
                        2*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*6/8))+ ...
                        4*sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*7/8))+ ...
                          sin(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*8/8)));
end