%% 计算X坐标
%% 输入参数：
%   dStartPoseX: 初始x坐标
%   dStartYaw: 初始角度
%   dA0: 0阶系数
%   dA1: 1阶系数
%   dA2：2阶系数
%   dA3: 3阶系数
%   dS：总长度
%% 输出参数：
%   dPoseX：计算得到X坐标
%% 调用说明：

function dPoseX=CalcPoseX(dStartPoseX,dStartYaw,dA0,dA1,dA2,dA3,dS)
dPoseX=dStartPoseX+dS/24*(cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,0))+ ...
                        4*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS/8))+ ...
                        2*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*2/8))+ ...
                        4*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*3/8))+ ...
                        2*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*4/8))+ ...
                        4*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*5/8))+ ...
                        2*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*6/8))+ ...
                        4*cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*7/8))+ ...
                          cos(CalcTheta(dStartYaw,dA0,dA1,dA2,dA3,dS*8/8)));
end